language: python
python: 2.7
install:
  - pip install --upgrade pip wheel  # pip >= 8.0 needed to be compatible with "manylinux" wheels, used by numpy >= 1.11
  - pip install flake8
  - pip install --editable .[sas]
script: ./travis-run-tests.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: ./travis-release-tag.sh
    on:
      branch: master
