language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  # For Pandas version 0.14, see http://neuro.debian.net/install_pkg.html?p=python-pandas
  - wget -O- http://neuro.debian.net/lists/precise.us-ca.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
  - sudo apt-key adv --recv-keys --keyserver hkp://pgp.mit.edu:80 0xA5D32F012649A5A9
  - sudo apt-get update -qq
  - sudo apt-get install python-numpy python-pandas python-tables python-yaml
install:
  - pip install flake8  # Not yet available in Debian stable
  - pip install sas7bdat
  - pip install click
  - pip install -r requirements.txt
script: make test-ci
